name: LotteryBox
version: 0.0.3
description: Chance-based lottery boxes

author: Gareth Coles

main: me.gserv.lotterybox.LotteryBox
database: false

softdepend: [Vault]

commands:
    chbox:
        description: Edits a lottery box
        usage: /<command> <name> <operation> [params]
        permission: lotterybox.chbox
    givekey:
        description: Gives a key to a player
        usage: /<command> <player> [item] [name]
        permission: lotterybox.givekey
    lsbox:
        description: Lists lottery boxes and gets information on them
        usage: /<command> [name] ["rewards"]
        permission: lotterybox.lsbox
    mkbox:
        description: Creates a lottery box
        usage: /<command> <name> [world] [x] [y] [z]
        permission: lotterybox.mkbox
    mkkey:
        description: Creates a box key
        usage: /<command> [name]
        permission: lotterybox.mkkey
    rmbox:
        description: Removes a lottery box
        usage: /<command> <name>
        permission: lotterybox.rmbox

permissions:
    lotterybox.*:
            children:
                - lotterybox.chbox
                - lotterybox.givekey
                - lotterybox.lsbox
                - lotterybox.mkbox
                - lotterybox.mkkey
                - lotterybox.rmbox
                - lotterybox.open
            description: All the LotteryBox permissions
    lotterybox.admin:
            children:
                - lotterybox.chbox
                - lotterybox.givekey
                - lotterybox.lsbox
                - lotterybox.mkbox
                - lotterybox.mkkey
                - lotterybox.rmbox
            description: All the LotteryBox admin commands
    lotterybox.chbox:
        description: Access the /chbox command
    lotterybox.givekey:
        description: Access the /givekey command
    lotterybox.lsbox:
        description: Access the /lsbox command
    lotterybox.mkbox:
        description: Access the /mkbox command
    lotterybox.mkkey:
        description: Access the /mkkey command
    lotterybox.open:
        description: Open lottery boxes
    lotterybox.rmbox:
        description: Access the /rmbox command