name: LotteryBox
version: 0.0.1
description: Chance-based lottery boxes

author: Gareth Coles

main: me.gserv.lotterybox.LotteryBox
database: false

commands:
    mkbox:
        description: Creates a lottery box
        usage: /<command> <name> [world] [x] [y] [z]
        permission: lotterybox.mkbox

permissions:
    lotterybox.*:
        children:
            - lotterybox.mkbox
        description: All the LotteryBox permissions
    lotterybox.mkbox:
        description: Access the /mkbox command