name: LotteryBox
version: 0.0.1
description: Chance-based lottery boxes

author: Gareth Coles

main: me.gserv.lotterybox.LotteryBox
database: false

permissions:
    lotterybox.*:
        children:
            - lotterybox.bypass
        description: All the BasePlugin permissions
    lotterybox.bypass:
        description: Bypass the example chat listener